[package]
name = "rustbuch_bindings_java-jni"
version = "0.1.0"
edition = "2018"

[dependencies]
jni = "0.19.0"
tokio = { version = "1", features = ["full"] }
lazy_static = "1.4.0"

[lib]
crate_type = ["cdylib"]