[package]
name = "own_0_hello_world"
version = "0.1.0"
authors = ["Dominik Gruber <dominik-gruber@live.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hello_world"
path = "src/hello_world.rs"